adding txt file; todo check branch build, add release-rc-filters, remove <<pipeline.parameters.det-version>>

diff --git a/.circleci/real_config.yml b/.circleci/real_config.yml
--- a/.circleci/real_config.yml
+++ b/.circleci/real_config.yml
@@ -95,6 +95,15 @@ release-filters: &release-filters
     only:
       - /(\d)+(\.(\d)+)+/
 
+release-dryrun: &release-dryrun
+  branches:
+    ignore:
+      - /.*/
+  tags:
+    only:
+      # Tags like: v3.1.3+dryrun
+      - /v\d+\.\d+\.\d+\+dryrun/
+
 upstream-feature-branch: &upstream-feature-branch
   branches:
     ignore:
@@ -1486,6 +1495,21 @@ commands:
     steps:
       - run: 
           command: pkill -SIGHUP -f "devcluster" && rm -rf /tmp/devcluster/lock
+
+  read-supported-versions:
+    steps:
+      - run:
+          name: Read Versions from File
+          command: |
+            VERSION_FILE="supported_versions.txt"
+            if [ -f "$VERSION_FILE" ]; then
+              SUPPORTED_VERSIONS=$(cat "$VERSION_FILE" | tr '\n' ' ')
+              # Export the variable to use in the matrix job
+              echo "export SUPPORTED_VERSIONS=\"$SUPPORTED_VERSIONS\"" >> $BASH_ENV
+            else
+              echo "Version file not found!"
+              exit 1
+            fi
 
   make-component:
     description: "Basic parameterized version of make for building Determined components."
@@ -3150,7 +3174,9 @@ jobs:
             - run: 
                 name: Fetch Tags & Checkout <<parameters.det-version>> Version
                 command: git fetch --tags && git checkout tags/<<parameters.det-version>>
-            - run: # given branch name, find most recent build, & substitute in ... ?
+            - run: 
+                name: Fetch Release Branch & checkout
+                command: # given branch name, find most recent build, & substitute in ... ?
             # 1. checkout git branch
             # 2. iterate through SHAs & check which is a match (for master, agent, etc) in docker image registry
             # 3. take first match & git fetch that SHA
@@ -4803,6 +4829,8 @@ workflows:
           name: build-go-ee
           context: github-read
 
+      - read-supported-versions
+
       - test-e2e:
           name: test-e2e-rbac
           context:
@@ -4815,7 +4843,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-cpu
@@ -4830,7 +4858,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-cpu-double
@@ -4847,7 +4875,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-cpu-oauth
@@ -4862,7 +4890,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-cpu-model-registry-rbac
@@ -4877,7 +4905,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-managed-devcluster
@@ -4897,7 +4925,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-managed-devcluster-resource-pools
@@ -4915,7 +4943,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-multi-k8s
@@ -4933,7 +4961,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-single-k8s
@@ -4949,7 +4977,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-port-registry
@@ -4964,7 +4992,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-cpu-elastic
@@ -4980,7 +5008,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-postgres10-with-ssl
@@ -4996,7 +5024,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-postgres14-with-ssl
@@ -5012,7 +5040,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-old-agent-versions
@@ -5027,7 +5055,7 @@ workflows:
           matrix:
             parameters:
               agent-version: ["0.17.10"]
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
           upgrade: true
 
       - test-e2e:
@@ -5044,7 +5072,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
       - test-e2e:
           name: test-e2e-saml
@@ -5059,7 +5087,7 @@ workflows:
           upgrade: true
           matrix:
             parameters:
-              det-version: *det-versions
+              det-version: << pipeline.parameters.SUPPORTED_VERSIONS >>
 
   test-e2e-longrunning:
     <<: *do-not-run-on-manual-trigger
